:: BUILDER SETTINGS
set charset="empty"
set project_folder="pliki"
set parser_version="0.1.11"
cd "%project_folder%"
echo "Usunięcie starych plików."
del /s /f /q en
mkdir en
cd ../
echo "Przekonwertowanie plików z ck3 na standardowe pliki yml."
::game
::główny
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english" "pliki\\en\\game\\localization\\english" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\bookmark" "pliki\\en\\\game\\localization\\english\\bookmark" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\credits" "pliki\\en\\\game\\localization\\english\\credits" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\culture" "pliki\\en\\\game\\localization\\english\\culture" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\custom_localization" "pliki\\en\\\game\\localization\\english\\custom_localization" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\dynasties" "pliki\\en\\\game\\localization\\english\\dynasties" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\dynasty_legacies" "pliki\\en\\\game\\localization\\english\\dynasty_legacies" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\enum" "pliki\\en\\\game\\localization\\english\\enum" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization" "pliki\\en\\\game\\localization\\english\\event_localization" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\gui" "pliki\\en\\\game\\localization\\english\\gui" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\interactions" "pliki\\en\\\game\\localization\\english\\interactions" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\lifestyles" "pliki\\en\\\game\\localization\\english\\lifestyles" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\load_tips" "pliki\\en\\\game\\localization\\english\\load_tips" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\modifiers" "pliki\\en\\\game\\localization\\english\\modifiers" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\names" "pliki\\en\\\game\\localization\\english\\names" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\opinions" "pliki\\en\\\game\\localization\\english\\opinions" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\portraits" "pliki\\en\\\game\\localization\\english\\portraits" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\religion" "pliki\\en\\\game\\localization\\english\\religion" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\triggers" "pliki\\en\\\game\\localization\\english\\triggers" "%charset%"
::event_localization
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\activities" "pliki\\en\\\game\\localization\\english\\event_localization\\activities" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\childhood" "pliki\\en\\\game\\localization\\english\\event_localization\\childhood" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\councillor_task_events" "pliki\\en\\\game\\localization\\english\\event_localization\\councillor_task_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\culture_events" "pliki\\en\\\game\\localization\\english\\event_localization\\culture_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\death_events" "pliki\\en\\\game\\localization\\english\\event_localization\\death_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\decisions" "pliki\\en\\\game\\localization\\english\\event_localization\\decisions" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\experimental" "pliki\\en\\\game\\localization\\english\\event_localization\\experimental" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\government_events" "pliki\\en\\\game\\localization\\english\\event_localization\\government_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\prison_events" "pliki\\en\\\game\\localization\\english\\event_localization\\prison_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\relation_events" "pliki\\en\\\game\\localization\\english\\event_localization\\relation_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\religion_events" "pliki\\en\\\game\\localization\\english\\event_localization\\religion_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\secret_events" "pliki\\en\\\game\\localization\\english\\event_localization\\secret_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\story_cycles" "pliki\\en\\\game\\localization\\english\\event_localization\\story_cycles" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\stress_events" "pliki\\en\\\game\\localization\\english\\event_localization\\stress_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\trait_specific_events" "pliki\\en\\\game\\localization\\english\\event_localization\\trait_specific_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\yearly_events" "pliki\\en\\\game\\localization\\english\\event_localization\\yearly_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\war_event" "pliki\\en\\\game\\localization\\english\\event_localization\\war_event" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\governance" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\governance" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\guile" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\guile" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\nickname" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\nickname" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\scholarship" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\scholarship" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\statecraft" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\statecraft" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\lifestyle\\warfare" "pliki\\en\\\game\\localization\\english\\event_localization\\lifestyle\\warfare" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\councillor_task_events\\councillor_spouse_events" "pliki\\en\\\game\\localization\\english\\event_localization\\councillor_task_events\\councillor_spouse_events" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\abduct" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\abduct" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\befriend" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\befriend" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\claim_throne" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\claim_throne" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\court" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\court" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\fabricate_hook" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\fabricate_hook" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\murder" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\murder" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\seduce" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\seduce" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\event_localization\\schemes\\sway" "pliki\\en\\\game\\localization\\english\\event_localization\\schemes\\sway" "%charset%"
::jomini
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization" "pliki\\en\\jomini\\localization" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\achievements" "pliki\\en\\jomini\\localization\\achievements" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\credits" "pliki\\en\\jomini\\localization\\credits" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\frontend" "pliki\\en\\jomini\\localization\\frontend" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\jomini" "pliki\\en\\jomini\\localization\\jomini" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\pops" "pliki\\en\\jomini\\localization\\pops" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\settings" "pliki\\en\\jomini\\localization\\settings" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\social" "pliki\\en\\jomini\\localization\\social" "%charset%"
::jomini\\jomini
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\jomini\\coat_of_arms" "pliki\\en\\jomini\\localization\\jomini\\coat_of_arms" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\jomini\\map_editor" "pliki\\en\\jomini\\localization\\jomini\\map_editor" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\jomini\\multiplayer_gui" "pliki\\en\\jomini\\localization\\jomini\\multiplayer_gui" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\jomini\\localization\\jomini\\script_system" "pliki\\en\\jomini\\localization\\jomini\\script_system" "%charset%"
::clausewitz
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\clausewitz\\localization" "pliki\\en\\clausewitz\\localization" "%charset%"
java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\clausewitz\\localization\\text_utils" "pliki\\en\\clausewitz\\localization\\text_utils" "%charset%"

::dlc

java -jar "tools\\LocaleParser\\bin\\LocaleParser-%parser_version%-SNAPSHOT.jar" "folder_to_yaml" "orginal\\game\\localization\\english\\dlc\\fp1" "pliki\\en\\game\\localization\\english\\dlc\\fp1" "%charset%"



echo "Koniec."
pause